package es.uma.Semantics;

import java.util.List;

public enum Domain {
    // Example instances:
    // Example1: This is an instance generated by our Simple-LLM instances generator
    // Example2: This is a real instance generated by a human modeler
    // Example3: This could be an instance generated by current state of the art generators
    EXAMPLE1(List.of("Bank.country", "Bank.name", "Person.firstName", "Person.lastName")),
    EXAMPLE2(List.of("Bank.country", "Bank.name", "Person.firstName", "Person.lastName")),
    EXAMPLE3(List.of("Bank.country", "Bank.name", "Person.firstName", "Person.lastName")),

    ADDRESSBOOK(List.of("Person.name", "Company.name", "Person.title", "Address.city", "Address.street", "Note.comment", "Company.industry")),
    BANK(List.of("Bank.country", "Bank.name", "Person.firstName", "Person.lastName")),
    FOOTBALL(List.of("Club.name", "Player.name", "Club.homeGround", "Club.chairman", "Competition.type", "MatchNote.note", "TrainingSession.location", "TrainingSession.purpose", "TrainingFailedToAttend.reason", "TrainingObjective.areaToImprove")),
    HOTELMANAGEMENT(List.of("Customer.firstName", "Customer.lastName", "RoomExtra.description","FreeRoomTypesDTO.roomTypeDescription")),
    MYEXPENSES(List.of("Bill.category", "Comment.text", "Currency.name")),
    PICKUPNET(List.of("Driver.name", "Address.text")),
    RESTAURANT(List.of("Owner.name", "RegularCustomer.name", "Manager.name", "HeadWaiter.name", "Waiter.name", "Cook.name", "BusDriver.name", "Chef.name", "Table.description")),
    STATEMACHINE(List.of("StateMachine.name", "State.name", "Transition.name")),
    VEHICLERENTAL(List.of("RentalOffice.name", "Individual.name", "Company.name", "RentalOffice.address")),
    VIDEOCLUB(List.of("Movie.title", "Series.title", "Actor.name"));

    private final List<String> attributes;

    Domain(List<String> attributes) {
        this.attributes = attributes;
    }

    public List<String> getAttributes() {
        return attributes;
    }
}
